### ISSUE TITLE
Kodi 20 Komptibilität

### ISSUE THREAD

**Issue by probonopd** [dojomo/plugin.video.mediathekdirekt#4]
In allen Dateien muss `xbmc.translatePath` durch `xbmcvfs.translatePath` ersetzt werden und in den betroffenen Dateien muss, soweit nicht bereits vorhanden, `import xbmcvfs` hinzugefügt werden. Dann läuft es auf Kodi 20, das habe ich getestet. Ob es dann auf Kodi 18 und 19 auch noch läuft habe ich allerdings noch nicht testen können.

**Comment by dojomo** [comment]
Danke für die Info. Sorry das es so lange gedauert hat. Die App sollte jetzt ab Version 1.0.3+matrix.1 auch Nexus kompatibel sein. Die neuste Version findest du hier: https://github.com/dojomo/plugin.video.mediathekdirekt/tags

**Comment by probonopd** [comment]
Dankeschön!
