### ISSUE TITLE
Icon und Benachrichtigung

### ISSUE THREAD

**Issue by Markus0000000** [dojomo/plugin.video.mediathekdirekt#6]
@mojodo: Wäre auch noch toll, wenn das Icon auf die Icon-Datei unter resources/images/ verweist:

Quellcode

    -- icon = os.path.join(addonDir,'icon.png')
    ++ icon = os.path.join(addonDir,'resources/images/icon.png')

Ich bekomme beim Speichern einer Sendung immer eine Fehlermeldung. Bei mir funktioniert folgende Lösung:
Quellcode

    -- dialog.ok(addonID, translation(30101), str(fullPath))
    ++ Nachricht = translation(30101)+' '+fullPath
    ++ dialog.notification('MediathekDirekt', Nachricht, icon, 8000)

**Comment by dojomo** [comment]
@Markus0000000: ist gefixt in Version 1.0.3+matrix.2 https://github.com/dojomo/plugin.video.mediathekdirekt/tags
